name: ccsdev
dependencies:
    - python=2.7.12
    - nose
    - pandas=0.19.2
    - pip: 
        - toolz==0.8.2
        - pyparsing==2.2.0
        - git+https://github.com/jcrudy/clinvoc.git@6e490ba3cd8f3e326611d3f223ac0a8434115f43
